#!/bin/sh

systemctl stop connman

iptables -F
iptables -i wlan0 -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -i wlan0 -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -i wlan0 -A INPUT -p udp --dport 53 -j ACCEPT
iptables -i wlan0 -A INPUT -p udp --dport 67:68 -j ACCEPT
iptables -i wlan0 -A INPUT -j DROP
iptables -t nat -A PREROUTING -p tcp --dport 0:49151 -j DNAT --to-destination 19

ifconfig wlan0 up
ifconfig wlan0 192.168.1.90

systemctl start hostapd
systemctl start dnsmasq
